apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd-projects
spec:
  # Automatically synchronize changes from sources, create Consul namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

  project: consul

  sources:
    # Deploy Consul Helm chart
    - chart: consul
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 1.2.2
      helm:
        releaseName: consul
        valueFiles:
          - $values/consul-helm-values.yaml

    # Use values from demo repository for Helm chart
    - repoURL: 'https://github.com/rafaeldihl/argocd.git'
      targetRevision: main
      ref: values

    # Use Consul CRDs to configure proxy-defaults and mesh
    - repoURL: 'https://github.com/rafaeldihl/argocd.git'
      path: ./
      targetRevision: main

  # Deploy to the consul namespace in same cluster
  destination:
    server: "https://kubernetes.default.svc"
    namespace: consul
