apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  meshGateway:
    mode: 'local'
  config:
    # omitted for clarity
